from GerenciamentoUI.Localizacoes.tr_08_OpcoesSobre import (LICENSE_TEXT_ES_ES, 
                                                            NOTICE_TEXT_ES_ES, 
                                                            ABOUT_TEXT_ES_ES, 
                                                            Privacy_Policy_es_ES)

traducoes_es_ES = {
    "access_date": "Fecha de Acceso",
    "size": "Tamaño",
    "attributes": "Atributos", 
    "author": "Autor",
    "dimensions": "Dimensiones",
    "duration": "Duración", 
    "bit_rate": "Tasa de Bits",
    "protected": "Protegido",
    "configure_columns": "Configurar Columnas",
    "yes": "Sí",
    "no": "No",
    "close": "Cerrar",
    "readonly": "Solo Lectura",
    "hidden": "Oculto",
    "system": "Sistema",
    "archive": "Archivo",
    "encrypted": "Cifrado",
    "compressed": "Comprimido",
    "xls": "Autor Desconocido - Excel",
    "access": "Autor Desconocido - Access", 
    "outllok": "Autor Desconocido - Outlook",
    "publisher": "Autor Desconocido - Publisher",
    "visio": "Autor Desconocido - Visio",
    "project": "Autor Desconocido - Project",
    "unknown_author": "Autor Desconocido",
    "text_html": "Autor Desconocido",
    "compressed_file": "Autor Desconocido - Archivo Comprimido",
    "window_title": "Panoptes Patrol",
    "select_dir": "Seleccionar Directorio:",
    "start_stop": "Iniciar/Detener Análisis:",
    "export_excel": "Exportar Excel:",
    "export_csv": "Exportar CSV:",
    "export_txt": "Exportar TXT:",
    "export_json": "Exportar JSON:",
    "export_xml": "Exportar XML:",
    "export_db": "Exportar DB:",
    "clear_data": "Limpiar Datos:",
    "no_dir": "Ningún directorio seleccionado",
    "select_to_start": "Seleccione un directorio para comenzar",
    "dir_selected": "Directorio seleccionado: {}",
    "warning": "Advertencia",
    "select_first": "¡Seleccione un directorio primero!",
    "monitoring_started": "Monitoreo iniciado...",
    "monitoring_stopped": "Monitoreo detenido.",
    "data_cleared": "Datos limpiados.",
    "operation_type": "Tipo de Operación",
    "name": "Nombre",
    "prev_dir": "Directorio Anterior",
    "curr_dir": "Directorio Actual",
    "creation_date": "Fecha de Creación",
    "modification_date": "Fecha de Modificación",
    "type": "Tipo",
    "op_moved": "Movido",
    "op_renamed": "Renombrado",
    "op_added": "Añadido", 
    "op_deleted": "Eliminado",
    "op_modified": "Modificado",
    "op_scanned": "Escaneado",
    "folder": "Carpeta",
    "unknown": "Desconocido", 
    "no_data": "¡No hay datos para exportar!",
    "operation_filter": "Filtrar por Operación",
    "search": "Buscar",
    "extension_filter": "Filtrar por Extensión",
    "date_filter": "Filtrar por Fecha",
    "start_date": "Fecha Inicial",
    "end_date": "Fecha Final",
    "clear_filters": "Limpiar Filtros:",
    "file_menu": "Archivo",
    "settings": "Configuración",
    "options_menu": "Opciones",
    "filters": "Filtros",
    "language": "Idioma",
    "statistics": "Estadísticas:",
    "save_all": "Guardar Todo",
    "select_save_dir": "Seleccionar Directorio para Guardar:",
    "save_as": "Guardar como:",
    "save": "Guardar:",
    "exit": "Salir",
    "no_data_to_plot": "No hay datos para graficar.",
    "success": "Éxito",
    "graphs_saved": "¡Gráficos guardados exitosamente!",
    "scanning": "Escaneando...",
    "operation_timeout": "La operación tardó demasiado y fue interrumpida.",
    "memory_usage_high": "Se detectó un alto uso de memoria.",
    "error": "Error",
    "dir_create_error": "Error al crear el directorio",
    "file_saved": "¡Archivo guardado con éxito!",
    "save_incomplete": "¡Exportación incompleta!",
    "save_error": "¡Error al exportar datos!",
    "operations_pie": "Gráfico de Pastel",
    "file_types": "Gráfico de Barras",
    "timeline": "Línea de Tiempo",
    "tree_map": "Mapa de Árboles",
    "hour_histogram": "Histograma de Horas",
    "pareto_analysis": "Diagrama de Pareto",
    "operations_by_day": "Operaciones por Día",
    "all_graphs_failed": "¡Fallo al guardar todos los gráficos!",
    "refresh": "Actualizar",
    "stats_error": "¡Error al generar estadísticas!",
    "failure": "Fallo",
    "graphs_saved_detail": "Gráficos guardados con éxito",
    "ok": "OK",
    "open_folder": "Abrir Carpeta",
    "save_graphs_error": "¡Error al guardar gráficos!",
    "confirm": "Confirmar",
    "clear_confirm": "¿Estás seguro de que deseas borrar los datos?",
    "clear_success": "¡Datos borrados con éxito!",
    "clear_error": "¡Error al borrar los datos!",
    "preparing_scan": "Preparando escaneo...",
    "remaining": "Restante",
    "scan_complete": "¡Escaneo completado!",
    "items": "Elementos",
    "file_directory": "Directorio",
    "file_image": "Imagen",
    "file_audio": "Audio",
    "file_video": "Video",
    "file_document": "Documento",
    "file_spreadsheet": "Hoja de Cálculo",
    "file_presentation": "Presentación",
    "file_database": "Base de Datos",
    "file_source_code": "Código Fuente",
    "file_compressed": "Comprimido",
    "file_executable": "Ejecutable",
    "file_other": "Otro",
    "file_temp": "Temporal",
    "file_archive": "Comprimido",
    "file_unknown": "Archivo Desconocido",
    "file_backup": "Respaldo",
    "file_log": "Registro",
    "file_config": "Configuración",
    "temporary_file": "Archivo Temporal",
    "events_monitored": "Eventos Monitoreados",
    "advanced_filters": "Filtros Avanzados",
    "reset_columns": "Restablecer Columnas",
    "columns_reset_success": "¡Columnas restablecidas con éxito!",
    "quantity": "Cantidad",
    "date_time": "Fecha/Hora",
    "date": "Fecha",
    "hour_of_day": "Hora del Día",
    "cumulative_percentage": "Porcentaje Acumulado",
    "quantity_by_type": "Cantidad por Tipo",
    "total_operations": "Total de Operaciones",
    "total": "Total",
    "language_change_confirm": "¿Realmente desea restablecer el idioma?",
    "language_change_error": "Error al cambiar el idioma: {}",
    "language_changed_success": "¡Idioma cambiado con éxito!",
    "restart_error": "Error al reiniciar la aplicación: {}",
    "export_error": "Error de Exportación",
    "export_error_details": "Error al exportar a {}: {}\n\nDetalles: {}",
    "export_preparation_error": "Error al preparar la exportación: {}\n\nDetalles: {}",
    "export_success": "Archivo exportado con éxito a {}",
    "no_graphs_saved": "No se guardaron gráficos con éxito",
    "show_details": "Mostrar Detalles",
    "hide_details": "Ocultar Detalles",
    "version": "Versión",
    "authors": "Autores",
    "description": "Descripción",
    "description_text": "Gestor de archivos y carpetas que monitorea cambios en un directorio específico",
    "about": "Acerca de",
    "licenses": "Licencias",
    "show_licenses": "Mostrar Licencias",
    "hide_licenses": "Ocultar Licencias",
    "site_oficial": "Sitios Oficiales de las Licencias",
    "notices": "Avisos",
    "show_notices": "Mostrar Avisos",
    "hide_notices": "Ocultar Avisos",
    "show_privacy_policy": "Mostrar Política de Privacidad",
    "hide_privacy_policy": "Ocultar Política de Privacidad",
    "visible_filters": "Filtros Visibles",
    "total_monitored": "Total Monitoreado",
    "lines": "Líneas",
    "words": "Palabras",
    "pages": "Páginas",
    "pages_estimated": "Páginas Estimadas",
    "paragraphs": "Párrafos",
    "slides": "Diapositivas",
    "slides_estimated": "Diapositivas Estimadas",
    "files": "Archivos",
    "unzipped": "Descomprimidos",
    "spreadsheets": "Hojas de Cálculo",
    "columns": "Columnas",
    "tables": "Tablas",
    "lines_code": "Líneas de Código",
    "total_lines": "Total de Líneas",
    "and_others": "y otros",
    "ignored": "Ignorados",
    "log_of": "Log de",
    "information_not_available": "Información no disponible",
    "ignore_move_filter": "Ignorar filtro de fecha para archivos movidos",
    "ignore_rename_filter": "Ignorar filtro de data para arquivos renomeados",
    "ignore_add_filter": "Ignorar filtro de data para arquivos adicionados",
    "ignore_delete_filter": "Ignorar filtro de data para arquivos excluídos",
    "ignore_modified_filter": "Ignorar filtro de fecha para archivos modificados",
    "ignore_scanned_filter": "Ignorar filtro de fecha para archivos escaneados",
    "select_all_columns": "Seleccionar Todas las Columnas",
    "configure_colors": "Configurar Colores",
    "operation_colors": "Colores de Operación",
    "reset_colors": "Restablecer Colores",
    "reset_colors_confirm": "¿Desea restablecer todos los colores a los valores predeterminados?",
    "colors_reset_success": "Colores restablecidos con éxito",
    "current": "Actual",
    "new": "Nuevo",
    "basics": "Básicos",
    "pastels": "Pasteles",
    "vibrant": "Vibrantes",
    "advanced_color_picker": "Selector de Color Avanzado",
    "cancel": "Cancelar",
    "select_color": "Seleccionar Color",
    "select_color_for": "Seleccionar color para",
    "color_changed_success": "¡Color cambiado con éxito!",
    "basic_colors": "Colores Básicos",
    "custom_colors": "Colores Personalizados",
    "pick_screen_color": "Seleccionar Color de Pantalla",
    "add_to_custom_colors": "Agregar a Colores Personalizados",
    "hue": "Tono",
    "sat": "Saturación",
    "val": "Valor",
    "red": "Rojo",
    "green": "Verde",
    "blue": "Azul",
    "records": "Registros",
    "records_estimated": "Registros Estimados",
    "bytes_per_record": "Bytes Por Registro",
    "bytes": "Bytes",
    "binary_file": "Binario",
    "minutes": "Minutos",
    "hours": "Horas",
    "days": "Días",
    "export_options": "Opciones de Exportación",
    "export_active_columns": "Exportar solo columnas activas",
    "export_active_filters": "Exportar solo filtros activos",
    "export_selected_data": "Exportar solo datos seleccionados",
    "reset_export_options": "Restaurar Valores Predeterminados",
    "export_options_reset_success": "¡Opciones de exportación restauradas a valores predeterminados!",
    "no_selection": "Ninguna celda seleccionada para exportación.",
    "size_distribution": "Distribución de Tamaños",
    "file_size_analysis": "Análisis de Tamaños de Archivo",
    "temporal_distribution": "Distribución Temporal",
    "size_categories": "Categorías de Tamaño",
    "very_small": "Muy Pequeño",
    "small": "Pequeño", 
    "medium": "Medio",
    "large": "Grande",
    "very_large": "Muy Grande",
    "events_per_day": "Eventos por Día",
    "file_size_mb": "Tamaño del Archivo (MB)",
    "no_size_data": "No hay datos de tamaño disponibles",
    "boxplot_analysis": "Análisis de Distribución",
    "quartile_analysis": "Análisis de Cuartiles",
    "temporal_distribution": "Distribución Temporal",
    "file_size_analysis": "Análisis de Tamaños de Archivo",
    "file_operations_flow": "Flujo de Operaciones en Archivos",
    "operations_by_file_type": "Operaciones por Tipo de Archivo",
    "file_size_distribution": "Distribución de Tamaños de Archivo",
    "days_of_week": "Días de la Semana",
    "monday": "Lunes",
    "tuesday": "Martes",
    "wednesday": "Miércoles",
    "thursday": "Jueves",
    "friday": "Viernes",
    "saturday": "Sábado",
    "sunday": "Domingo",
    "week_days": "Días de la Semana",
    "insufficient_data_after_filtering": "Datos insuficientes después del filtrado",
    "plotly_required": "Biblioteca plotly necesaria para\ngenerar el Diagrama de Sankey\n\npip install plotly",
    "library_required": "Biblioteca necesaria",
    "install_instruction": "Para instalar, ejecute:",
    "time_milliseconds": "Tiempo (milisegundos)",
    "time_centiseconds": "Tiempo (centésimas de segundo)",
    "time_seconds": "Tiempo (segundos)",
    "time_minutes": "Tiempo (minutos)",
    "time_hours": "Tiempo (horas)",
    "time_days": "Tiempo (días)",
    "ms": "ms",
    "s": "s",
    "min": "min",
    "h": "h",
    "d": "d",
    "file_types": "Tipos de Archivo",
    "select_graphs": "Seleccionar Gráficos",
    "select_all": "Seleccionar Todos", 
    "save_selected": "Guardar Seleccionados",
    "selected": "Seleccionados",
    "no_graphs_selected": "Ningún gráfico seleccionado",
    "selected_graphs_saved_detail": "Gráficos seleccionados guardados: {}/{} en {}",
    "hide_selection_panel": "Ocultar Panel de Selección",
    "expand_selection_panel": "Expandir Panel de Selección",
    "notice_text": NOTICE_TEXT_ES_ES,
    "about_text": ABOUT_TEXT_ES_ES,
    "license_text": LICENSE_TEXT_ES_ES,
    "privacy_policy_text": Privacy_Policy_es_ES
}
