from GerenciamentoUI.Localizacoes.tr_08_OpcoesSobre import (LICENSE_TEXT_DE_DE, 
                                                            NOTICE_TEXT_DE_DE, 
                                                            ABOUT_TEXT_DE_DE, 
                                                            Privacy_Policy_de_DE)

traducoes_de_DE = {
    "access_date": "Zugriffsdatum",
    "size": "Größe",
    "attributes": "Attribute",
    "author": "Autor",
    "dimensions": "Abmessungen",
    "duration": "Dauer",
    "bit_rate": "Bitrate",
    "protected": "Geschützt",
    "configure_columns": "Spalten konfigurieren",
    "yes": "Ja",
    "no": "Nein",
    "close": "Schließen",
    "readonly": "Schreibgeschützt",
    "hidden": "Versteckt",
    "system": "System",
    "archive": "Archiv",
    "encrypted": "Verschlüsselt",
    "compressed": "Komprimiert",
    "xls": "Unbekannter Autor - Excel",
    "access": "Unbekannter Autor - Access",
    "outllok": "Unbekannter Autor - Outlook",
    "publisher": "Unbekannter Autor - Publisher",
    "visio": "Unbekannter Autor - Visio",
    "project": "Unbekannter Autor - Project",
    "unknown_author": "Unbekannter Autor",
    "text_html": "Unbekannter Autor",
    "compressed_file": "Unbekannter Autor - Komprimierte Datei",
    "window_title": "Panoptes Patrol",
    "select_dir": "Verzeichnis auswählen:",
    "start_stop": "Analyse starten/stoppen:",
    "export_excel": "Excel exportieren:",
    "export_csv": "CSV exportieren:",
    "export_txt": "TXT exportieren:",
    "export_json": "JSON exportieren:",
    "export_xml": "XML exportieren:",
    "export_db": "DB exportieren:",
    "clear_data": "Daten löschen:",
    "no_dir": "Kein Verzeichnis ausgewählt",
    "select_to_start": "Wählen Sie ein Verzeichnis zum Starten",
    "dir_selected": "Ausgewähltes Verzeichnis: {}",
    "warning": "Warnung",
    "select_first": "Bitte wählen Sie zuerst ein Verzeichnis aus!",
    "monitoring_started": "Überwachung gestartet...",
    "monitoring_stopped": "Überwachung gestoppt.",
    "data_cleared": "Daten gelöscht.",
    "operation_type": "Operationstyp",
    "name": "Name",
    "prev_dir": "Vorheriges Verzeichnis",
    "curr_dir": "Aktuelles Verzeichnis",
    "creation_date": "Erstellungsdatum",
    "modification_date": "Änderungsdatum",
    "type": "Typ",
    "op_moved": "Verschoben",
    "op_renamed": "Umbenannt",
    "op_added": "Hinzugefügt",
    "op_deleted": "Gelöscht",
    "op_modified": "Geändert",
    "op_scanned": "Gescannt",
    "folder": "Ordner",
    "unknown": "Unbekannt",
    "no_data": "Keine Daten zum Exportieren!",
    "operation_filter": "Nach Operation filtern",
    "search": "Suchen",
    "extension_filter": "Nach Erweiterung filtern",
    "date_filter": "Nach Datum filtern",
    "start_date": "Startdatum",
    "end_date": "Enddatum",
    "clear_filters": "Filter zurücksetzen:",
    "file_menu": "Datei",
    "settings": "Einstellungen",
    "options_menu": "Optionen",
    "filters": "Filter",
    "language": "Sprache",
    "statistics": "Statistik:",
    "no_data_to_plot": "Keine Daten zum Plotten.",
    "save_as": "Speichern unter:",
    "save": "Speichern",
    "exit": "Beenden",
    "save_all": "Alles speichern",
    "select_save_dir": "Speicherordner wählen",
    "success": "Erfolg",
    "graphs_saved": "Diagramme erfolgreich gespeichert",
    "scanning": "Scannen...",
    "operation_timeout": "Der Vorgang dauerte zu lange und wurde unterbrochen.",
    "memory_usage_high": "Hohe Speicherauslastung erkannt.",
    "error": "Fehler",
    "dir_create_error": "Fehler beim Erstellen des Verzeichnisses",
    "file_saved": "Datei erfolgreich gespeichert!",
    "save_incomplete": "Unvollständiger Export!",
    "save_error": "Fehler beim Exportieren der Daten!",
    "operations_pie": "Kuchendiagramm",
    "file_types": "Balkendiagramm",
    "timeline": "Zeitleiste",
    "tree_map": "Baumkarte",
    "hour_histogram": "Stündliches Histogramm",
    "pareto_analysis": "Pareto-Diagramm",
    "operations_by_day": "Operationen pro Tag",
    "all_graphs_failed": "Fehler beim Speichern aller Diagramme!",
    "refresh": "Aktualisieren",
    "stats_error": "Fehler bei der Statistikerstellung!",
    "failure": "Fehlschlag",
    "graphs_saved_detail": "Diagramme erfolgreich gespeichert",
    "ok": "OK",
    "open_folder": "Ordner öffnen",
    "save_graphs_error": "Fehler beim Speichern der Diagramme!",
    "confirm": "Bestätigen",
    "clear_confirm": "Sind Sie sicher, dass Sie die Daten löschen möchten?",
    "clear_success": "Daten erfolgreich gelöscht!",
    "clear_error": "Fehler beim Löschen der Daten!",
    "preparing_scan": "Scan wird vorbereitet...",
    "remaining": "Verbleibend",
    "scan_complete": "Scan abgeschlossen!",
    "items": "Elemente",
    "file_directory": "Verzeichnis",
    "file_image": "Bild",
    "file_audio": "Audio",
    "file_video": "Video",
    "file_document": "Dokument",
    "file_spreadsheet": "Tabellenkalkulation",
    "file_presentation": "Präsentation",
    "file_database": "Datenbank",
    "file_source_code": "Quellcode",
    "file_compressed": "Komprimiert",
    "file_executable": "Ausführbar",
    "file_other": "Andere",
    "file_temp": "Temporär",
    "file_archive": "Komprimiert",
    "file_unknown": "Unbekannte Datei",
    "file_backup": "Backup",
    "file_log": "Protokoll",
    "file_config": "Konfiguration",
    "temporary_file": "Temporäre Datei",
    "events_monitored": "Überwachte Ereignisse",
    "advanced_filters": "Erweiterte Filter",
    "reset_columns": "Spalten zurücksetzen",
    "columns_reset_success": "Spalten erfolgreich zurückgesetzt",
    "quantity": "Menge",
    "date_time": "Datum/Uhrzeit",
    "date": "Datum",
    "hour_of_day": "Tageszeit",
    "cumulative_percentage": "Kumulative Prozentzahl",
    "quantity_by_type": "Menge nach Typ",
    "total_operations": "Gesamte Operationen",
    "total": "Gesamt",
    "language_change_confirm": "Möchten Sie die Sprache wirklich zurücksetzen?",
    "language_change_error": "Fehler beim Ändern der Sprache: {}",
    "language_changed_success": "Sprache erfolgreich geändert!",
    "restart_error": "Fehler beim Neustart der Anwendung: {}",
    "export_error": "Exportfehler",
    "export_error_details": "Fehler beim Exportieren nach {}: {}\n\nDetails: {}",
    "export_preparation_error": "Fehler bei der Vorbereitung des Exports: {}\n\nDetails: {}",
    "export_success": "Datei erfolgreich nach {} exportiert",
    "no_graphs_saved": "Keine Diagramme wurden erfolgreich gespeichert",
    "show_details": "Details anzeigen",
    "hide_details": "Details ausblenden",
    "version": "Version",
    "authors": "Autoren",
    "description": "Beschreibung",
    "description_text": "Datei- und Ordnermanager, der Änderungen in einem bestimmten Verzeichnis überwacht",
    "about": "Über",
    "licenses": "Lizenzen",
    "show_licenses": "Lizenzen anzeigen",
    "hide_licenses": "Lizenzen ausblenden",
    "site_oficial": "Offizielle Lizenzseiten",
    "notices": "Hinweise",
    "show_notices": "Hinweise anzeigen",
    "hide_notices": "Hinweise ausblenden",
    "show_privacy_policy": "Datenschutzrichtlinie anzeigen",
    "hide_privacy_policy": "Datenschutzrichtlinie ausblenden",
    "visible_filters": "Sichtbare Filter",
    "total_monitored": "Gesamt überwacht",
    "lines": "Zeilen",
    "words": "Wörter",
    "pages": "Seiten",
    "pages_estimated": "Geschätzte Seiten",
    "paragraphs": "Absätze",
    "slides": "Folien",
    "slides_estimated": "Geschätzte Folien",
    "files": "Dateien",
    "unzipped": "Entpackt",
    "spreadsheets": "Tabellenkalkulationen",
    "columns": "Spalten",
    "tables": "Tabellen",
    "lines_code": "Codezeilen",
    "total_lines": "Gesamtzeilen",
    "and_others": "und andere",
    "ignored": "Ignoriert",
    "log_of": "Protokoll von",
    "information_not_available": "Information nicht verfügbar",
    "ignore_move_filter": "Ändern Sie den Datumsfilter für verschobene Dateien",
    "ignore_rename_filter": "Ändern Sie den Datumsfilter für umbenannte Dateien",
    "ignore_add_filter": "Ändern Sie den Datumsfilter für hinzugefügte Dateien",
    "ignore_delete_filter": "Ändern Sie den Datumsfilter für gelöschte Dateien",
    "ignore_modified_filter": "Ändern Sie den Datumsfilter für geänderte Dateien",
    "ignore_scanned_filter": "Ändern Sie den Datumsfilter für gescannte Dateien",
    "select_all_columns": "Alle Spalten Auswählen",
    "configure_colors": "Farben Konfigurieren",
    "operation_colors": "Betriebsfarben",
    "reset_colors": "Farben Zurücksetzen",
    "reset_colors_confirm": "Möchten Sie alle Farben auf die Standardwerte zurücksetzen?",
    "colors_reset_success": "Farben erfolgreich zurückgesetzt",
    "current": "Aktuell",
    "new": "Neu",
    "basics": "Grundlagen",
    "pastels": "Pastellfarben",
    "vibrant": "Lebendig",
    "advanced_color_picker": "Erweiterter Farbwähler",
    "cancel": "Abbrechen",
    "select_color": "Farbe Wählen",
    "select_color_for": "Farbe für auswählen",
    "color_changed_success": "Farbe erfolgreich geändert!",
    "basic_colors": "Basisfarben",
    "custom_colors": "Benutzerdefinierte Farben",
    "pick_screen_color": "Bildschirmfarbe auswählen",
    "add_to_custom_colors": "Zu benutzerdefinierten Farben hinzufügen",
    "hue": "Farbton",
    "sat": "Sättigung",
    "val": "Wert",
    "red": "Rot",
    "green": "Grün",
    "blue": "Blau",
    "records": "Datensätze",
    "records_estimated": "Geschätzte Datensätze",
    "bytes_per_record": "Bytes Pro Datensatz",
    "bytes": "Bytes",
    "binary_file": "Binär",
    "minutes": "Minuten",
    "hours": "Stunden",
    "days": "Tage",
    "export_options": "Exportoptionen",
    "export_active_columns": "Nur aktive Spalten exportieren",
    "export_active_filters": "Nur aktive Filter exportieren",
    "export_selected_data": "Nur ausgewählte Daten exportieren",
    "reset_export_options": "Standardeinstellungen wiederherstellen",
    "export_options_reset_success": "Exportoptionen auf Standardwerte zurückgesetzt!",
    "no_selection": "Keine Zellen für den Export ausgewählt.",
    "size_distribution": "Größenverteilung",
    "file_size_analysis": "Dateigrößenanalyse",
    "temporal_distribution": "Zeitliche Verteilung",
    "size_categories": "Größenkategorien",
    "very_small": "Sehr Klein",
    "small": "Klein", 
    "medium": "Mittel",
    "large": "Groß",
    "very_large": "Sehr Groß",
    "events_per_day": "Ereignisse pro Tag",
    "file_size_mb": "Dateigröße (MB)",
    "no_size_data": "Keine Größendaten verfügbar",
    "boxplot_analysis": "Verteilungsanalyse",
    "quartile_analysis": "Quartilanalyse",
    "temporal_distribution": "Zeitliche Verteilung",
    "file_size_analysis": "Dateigrößenanalyse",
    "file_operations_flow": "Dateioperationsfluss",
    "operations_by_file_type": "Operationen nach Dateityp",
    "file_size_distribution": "Dateigrößenverteilung",
    "days_of_week": "Wochentage",
    "monday": "Montag",
    "tuesday": "Dienstag",
    "wednesday": "Mittwoch",
    "thursday": "Donnerstag",
    "friday": "Freitag",
    "saturday": "Samstag",
    "sunday": "Sonntag",
    "week_days": "Wochentage",
    "insufficient_data_after_filtering": "Unzureichende Daten nach der Filterung",
    "plotly_required": "Plotly-Bibliothek erforderlich, um\nSankey-Diagramm zu generieren\n\npip install plotly",
    "library_required": "Bibliothek erforderlich",
    "install_instruction": "Zur Installation ausführen:",
    "time_milliseconds": "Zeit (Millisekunden)",
    "time_centiseconds": "Zeit (Hundertstelsekunden)",
    "time_seconds": "Zeit (Sekunden)",
    "time_minutes": "Zeit (Minuten)",
    "time_hours": "Zeit (Stunden)",
    "time_days": "Zeit (Tage)",
    "ms": "ms",
    "s": "s",
    "min": "min",
    "h": "h",
    "d": "T",
    "file_types": "Dateitypen",
    "select_graphs": "Diagramme Auswählen",
    "select_all": "Alle Auswählen", 
    "save_selected": "Ausgewählte Speichern",
    "selected": "Ausgewählt",
    "no_graphs_selected": "Keine Diagramme ausgewählt",
    "selected_graphs_saved_detail": "Ausgewählte Diagramme gespeichert: {}/{} in {}",
    "hide_selection_panel": "Auswahlbereich Ausblenden",
    "expand_selection_panel": "Auswahlbereich Erweitern",
    "notice_text": NOTICE_TEXT_DE_DE,
    "about_text": ABOUT_TEXT_DE_DE,
    "license_text": LICENSE_TEXT_DE_DE,
    "privacy_policy_text": Privacy_Policy_de_DE
}
