from GerenciamentoUI.Localizacoes.tr_08_OpcoesSobre import (LICENSE_TEXT_PT_BR, 
                                                            NOTICE_TEXT_PT_BR, 
                                                            ABOUT_TEXT_PT_BR, 
                                                            Privacy_Policy_pt_BR)

traducoes_pt_BR = {
    "access_date": "Data de Acesso",
    "size": "Tamanho",
    "attributes": "Atributos",
    "author": "Autor", 
    "dimensions": "Dimensões",
    "duration": "Duração",
    "bit_rate": "Taxa de Bits",
    "protected": "Protegido",
    "file_menu": "Arquivo",
    "settings": "Configurações",
    "options_menu": "Opções",
    "configure_columns": "Configurar Colunas",
    "filters": "Filtros",
    "language": "Idioma",
    "yes": "Sim",
    "no": "Não",
    "close": "Fechar",
    "readonly": "Somente Leitura",
    "hidden": "Oculto", 
    "system": "Sistema",
    "archive": "Arquivo",
    "encrypted": "Criptografado",
    "compressed": "Comprimido",
    "xls": "Autor Desconhecido - Excel",
    "access": "Autor Desconhecido - Access",
    "outllok": "Autor Desconhecido - Outlook",
    "publisher": "Autor Desconhecido - Publisher",
    "visio": "Autor Desconhecido - Visio",
    "project": "Autor Desconhecido - Project",
    "unknown_author": "Autor Desconhecido",
    "text_html": "Autor Desconhecido",
    "compressed_file": "Autor Desconhecido - Arquivo Comprimido",
    "window_title": "Panoptes Patrol",
    "select_dir": "Selecionar Diretório:",
    "start_stop": "Iniciar/Parar Análise:",
    "save_as": "Salvar como:",
    "save": "Salvar:",
    "exit": "Sair",
    "export_excel": "Exportar Excel:",
    "export_csv": "Exportar CSV:", 
    "export_txt": "Exportar TXT:",
    "export_json": "Exportar JSON:",
    "export_xml": "Exportar XML:",
    "export_db": "Exportar DB:",
    "statistics": "Estatísticas:",
    "clear_data": "Limpar Dados:",
    "save_all": "Salvar Todos",
    "select_save_dir": "Selecionar Diretório para Salvar:",
    "no_dir": "Nenhum diretório selecionado",
    "select_to_start": "Selecione um diretório para começar",
    "dir_selected": "Diretório selecionado: {}",
    "warning": "Aviso",
    "no_data_to_plot": "Não há dados para plotar.",
    "select_first": "Selecione um diretório primeiro!",
    "monitoring_started": "Monitoramento iniciado...",
    "monitoring_stopped": "Monitoramento parado.",
    "data_cleared": "Dados limpos.",
    "operation_type": "Tipo de Operação",
    "name": "Nome",
    "prev_dir": "Diretório Anterior",
    "curr_dir": "Diretório Atual", 
    "creation_date": "Data de Criação",
    "modification_date": "Data de Modificação",
    "type": "Tipo",
    "op_moved": "Movido",
    "op_renamed": "Renomeado",
    "op_added": "Adicionado", 
    "op_deleted": "Excluído",
    "op_modified": "Modificado",
    "op_scanned": "Escaneado",
    "folder": "Pasta",
    "unknown": "Desconhecido",
    "no_data": "Não há dados para exportar!",
    "success": "Sucesso",
    "graphs_saved": "Gráficos salvos com sucesso!",
    "operation_filter": "Filtrar por Operação",
    "search": "Buscar",
    "extension_filter": "Filtrar por Extensão",
    "date_filter": "Filtrar por Data",
    "start_date": "Data Inicial",
    "end_date": "Data Final",
    "clear_filters": "Limpar Filtros:",
    "scanning": "Escaneando...",
    "operation_timeout": "A operação demorou muito tempo e foi interrompida.",
    "memory_usage_high": "Uso elevado de memória detectado.",
    "error": "Erro",
    "dir_create_error": "Erro ao criar diretório",
    "file_saved": "Arquivo salvo com sucesso!",
    "save_incomplete": "Exportação incompleta!",
    "save_error": "Erro ao exportar dados!",
    "operations_pie": "Gráfico de Pizza",
    "file_types": "Gráfico de Barras",
    "timeline": "Linha do Tempo",
    "tree_map": "Mapa de Árvore",
    "hour_histogram": "Histograma de Horas",
    "pareto_analysis": "Diagrama de Pareto",
    "operations_by_day": "Operações por Dia",
    "all_graphs_failed": "Falha ao salvar todos os gráficos!",
    "refresh": "Atualizar",
    "stats_error": "Erro ao gerar estatísticas!",
    "failure": "Falha",
    "graphs_saved_detail": "Gráficos salvos com sucesso",
    "ok": "OK",
    "open_folder": "Abrir Pasta",
    "save_graphs_error": "Erro ao salvar gráficos!",
    "confirm": "Confirmar",
    "clear_confirm": "Tem certeza de que deseja limpar os dados?",
    "clear_success": "Dados limpos com sucesso!",
    "clear_error": "Erro ao limpar dados!",
    "preparing_scan": "Preparando varredura...",
    "remaining": "Restante",
    "scan_complete": "Varredura concluída!",
    "items": "Itens",
    "file_directory": "Diretório",
    "file_image": "Imagem",
    "file_audio": "Áudio",
    "file_video": "Vídeo",
    "file_document": "Documento",
    "file_spreadsheet": "Planilha",
    "file_presentation": "Apresentação",
    "file_database": "Banco de Dados",
    "file_source_code": "Código Fonte",
    "file_compressed": "Compactado",
    "file_executable": "Executável",
    "file_other": "Outro",
    "file_temp": "Temporário",
    "file_archive": "Compactado",
    "file_unknown": "Arquvo Desconhecido",
    "file_backup": "Backup",
    "file_log": "Registro",
    "file_config": "Configuração",
    "temporary_file": "Arquivo Temporário",
    "events_monitored": "Eventos Monitorados",
    "advanced_filters": "Filtros Avançados",
    "reset_columns": "Redefinir Colunas",
    "columns_reset_success": "Colunas redefinidas com sucesso!",
    "quantity": "Quantidade",
    "date_time": "Data/Hora",
    "date": "Data", 
    "hour_of_day": "Hora do Dia",
    "cumulative_percentage": "Porcentagem Acumulada",
    "quantity_by_type": "Quantidade por Tipo",
    "total_operations": "Total de Operações",
    "total": "Total",
    "language_change_confirm": "Deseja realmente redefinir o idioma?",
    "language_change_error": "Erro ao alterar o idioma: {}",
    "language_changed_success": "Idioma alterado com sucesso!",
    "restart_error": "Falha ao reiniciar o aplicativo: {}",
    "export_error": "Erro de Exportação",
    "export_error_details": "Erro ao exportar para {}: {}\n\nDetalhes: {}",
    "export_preparation_error": "Erro ao preparar exportação: {}\n\nDetalhes: {}",
    "export_success": "Arquivo exportado com sucesso para {}",
    "no_graphs_saved": "Nenhum gráfico foi salvo com sucesso",
    "show_details": "Mostrar Detalhes",
    "hide_details": "Ocultar Detalhes",
    "version": "Versão",
    "authors": "Autores",
    "description": "Descrição",
    "description_text": "Gerenciador de arquivos e pastas que monitora mudanças em um diretório específico",
    "about": "Sobre",
    "licenses": "Licenças",
    "show_licenses": "Mostrar Licenças",
    "hide_licenses": "Ocultar Licenças",
    "site_oficial": "Sites Oficiais das Licenças",
    "notices": "Avisos",
    "show_notices": "Mostrar Avisos",
    "hide_notices": "Ocultar Avisos",
    "show_privacy_policy": "Mostrar Política de Privacidade",
    "hide_privacy_policy": "Ocultar Política de Privacidade",
    "visible_filters": "Filtrados Visíveis",
    "total_monitored": "Total Monitorado",
    "lines": "Linhas",
    "words": "Palavras",
    "pages": "Páginas",
    "pages_estimated": "Páginas Estimadas",
    "paragraphs": "Parágrafos",
    "slides": "Slides",
    "slides_estimated": "Slides Estimados",
    "files": "Arquivos",
    "unzipped": "Descompactados",
    "spreadsheets": "Planilhas",
    "columns": "Colunas",
    "tables": "Tabelas",
    "lines_code": "Linhas de Código",
    "total_lines": "Total de Linhas",
    "and_others": "e outros",
    "ignored": "Ignorados",
    "log_of": "Log de",
    "information_not_available": "Informação não disponível",
    "ignore_move_filter": "Ignorar filtro de data para arquivos movidos",
    "ignore_rename_filter": "Ignorar filtro de data para arquivos renomeados",
    "ignore_add_filter": "Ignorar filtro de data para arquivos adicionados",
    "ignore_delete_filter": "Ignorar filtro de data para arquivos excluídos",
    "ignore_modified_filter": "Ignorar filtro de data para arquivos modificados",
    "ignore_scanned_filter": "Ignorar filtro de data para arquivos escaneados",
    "select_all_columns": "Selecionar Todas as Colunas",
    "configure_colors": "Configurar Cores",
    "operation_colors": "Cores de Operação",
    "reset_colors": "Restaurar Cores",
    "reset_colors_confirm": "Deseja restaurar todas as cores para os valores padrão?",
    "colors_reset_success": "Cores restauradas com sucesso!",
    "current": "Atual",
    "new": "Nova",
    "basics": "Básicas",
    "pastels": "Pastéis",
    "vibrant": "Vibrantes",
    "advanced_color_picker": "Seletor de Cores Avançado",
    "cancel": "Cancelar",
    "select_color": "Selecionar Cor",
    "select_color_for": "Selecionar cor para",
    "color_changed_success": "Cor alterada com sucesso!",
    "basic_colors": "Cores Básicas",
    "custom_colors": "Customizar Cores",
    "pick_screen_color": "Selecionar Cor da Tela",
    "add_to_custom_colors": "Adicionar às Cores Personalizadas",
    "hue": "Matiz",
    "sat": "Saturação",
    "val": "Valor",
    "red": "Vermelho",
    "green": "Verde",
    "blue": "Azul",
    "records": "Registros",
    "records_estimated": "Registros Estimados",
    "bytes_per_record": "bytes por registro",
    "bytes": "Bytes",
    "binary_file": "Binário",
    "minutes": "Minutos",
    "hours": "Horas",
    "days": "Dias",
    "export_options": "Opções de Exportação",
    "export_active_columns": "Exportar apenas colunas ativas",
    "export_active_filters": "Exportar apenas filtros ativos",
    "export_selected_data": "Exportar apenas dados selecionados",
    "reset_export_options": "Restaurar Padrões",
    "export_options_reset_success": "Opções de exportação restauradas para valores padrão!",
    "no_selection": "Nenhuma célula selecionada para exportação.",
    "size_distribution": "Distribuição de Tamanhos",
    "file_size_analysis": "Análise de Tamanhos de Arquivo",
    "temporal_distribution": "Distribuição Temporal",
    "size_categories": "Categorias de Tamanho",
    "very_small": "Muito Pequeno",
    "small": "Pequeno", 
    "medium": "Médio",
    "large": "Grande",
    "very_large": "Muito Grande",
    "events_per_day": "Eventos por Dia",
    "file_size_mb": "Tamanho do Arquivo (MB)",
    "no_size_data": "Não há dados de tamanho disponíveis",
    "boxplot_analysis": "Análise de Distribuição",
    "quartile_analysis": "Análise de Quartis",
    "temporal_distribution": "Distribuição Temporal",
    "file_size_analysis": "Análise de Tamanho de Arquivo",
    "file_operations_flow": "Fluxo de Operações em Arquivos",
    "operations_by_file_type": "Operações por Tipo de Arquivo",
    "file_size_distribution": "Distribuição de Tamanhos de Arquivo",
    "days_of_week": "Dias da Semana",
    "monday": "Segunda",
    "tuesday": "Terça",
    "wednesday": "Quarta",
    "thursday": "Quinta",
    "friday": "Sexta",
    "saturday": "Sábado",
    "sunday": "Domingo",
    "week_days": "Dias da Semana",
    "insufficient_data_after_filtering": "Sem dados suficientes após filtragem",
    "plotly_required": "Biblioteca plotly necessária para\ngerar o Diagrama de Sankey\n\npip install plotly",
    "library_required": "Biblioteca necessária",
    "install_instruction": "Para instalar, execute:",
    "time_milliseconds": "Tempo (milissegundos)",
    "time_centiseconds": "Tempo (centésimos de segundo)",
    "time_seconds": "Tempo (segundos)",
    "time_minutes": "Tempo (minutos)",
    "time_hours": "Tempo (horas)",
    "time_days": "Tempo (dias)",
    "ms": "ms",
    "s": "s",
    "min": "min",
    "h": "h",
    "d": "d",
    "file_types": "Tipos de Arquivo",
    "select_graphs": "Selecionar Gráficos",
    "select_all": "Selecionar Todos", 
    "save_selected": "Salvar Selecionados",
    "selected": "Selecionados",
    "no_graphs_selected": "Nenhum gráfico selecionado",
    "selected_graphs_saved_detail": "Gráficos selecionados salvos: {}/{} em {}",
    "hide_selection_panel": "Ocultar Painel de Seleção",
    "expand_selection_panel": "Expandir Painel de Seleção",
    "notice_text": NOTICE_TEXT_PT_BR,
    "about_text": ABOUT_TEXT_PT_BR,
    "license_text": LICENSE_TEXT_PT_BR,
    "privacy_policy_text": Privacy_Policy_pt_BR
}
