from GerenciamentoUI.Localizacoes.tr_08_OpcoesSobre import (LICENSE_TEXT_IT_IT, 
                                                            NOTICE_TEXT_IT_IT, 
                                                            ABOUT_TEXT_IT_IT, 
                                                            Privacy_Policy_it_IT)

traducoes_it_IT = {
    "access_date": "Data di Accesso",
    "size": "Dimensione",
    "attributes": "Attributi",
    "author": "Autore",
    "dimensions": "Dimensioni",
    "duration": "Durata",
    "bit_rate": "Bit Rate",
    "protected": "Protetto",
    "configure_columns": "Configura Colonne",
    "yes": "Sì",
    "no": "No",
    "close": "Chiudi",
    "readonly": "Sola Lettura",
    "hidden": "Nascosto",
    "system": "Sistema",
    "archive": "Archivio",
    "encrypted": "Criptato",
    "compressed": "Compresso",
    "xls": "Autore Sconosciuto - Excel",
    "access": "Autore Sconosciuto - Access",
    "outllok": "Autore Sconosciuto - Outlook",
    "publisher": "Autore Sconosciuto - Publisher",
    "visio": "Autore Sconosciuto - Visio",
    "project": "Autore Sconosciuto - Project",
    "unknown_author": "Autore Sconosciuto",
    "text_html": "Autore Sconosciuto",
    "compressed_file": "Autore Sconosciuto - File Compresso",
    "window_title": "Panoptes Patrol",
    "select_dir": "Seleziona Directory:",
    "start_stop": "Avvia/Ferma Analisi:",
    "export_excel": "Esporta Excel:",
    "export_csv": "Esporta CSV:",
    "export_txt": "Esporta TXT:",
    "export_json": "Exporta JSON:",
    "export_xml": "Exporta XML:",
    "export_db": "Exporta DB:",
    "clear_data": "Cancella Dati:",
    "no_dir": "Nessuna directory selezionata",
    "select_to_start": "Seleziona una directory per iniziare",
    "dir_selected": "Directory selezionata: {}",
    "warning": "Avviso",
    "select_first": "Seleziona prima una directory!",
    "monitoring_started": "Monitoraggio avviato...",
    "monitoring_stopped": "Monitoraggio fermato.",
    "data_cleared": "Dati cancellati.",
    "operation_type": "Tipo Operazione",
    "name": "Nome",
    "prev_dir": "Directory Precedente",
    "curr_dir": "Directory Attuale",
    "creation_date": "Data Creazione",
    "modification_date": "Data Modifica",
    "type": "Tipo",
    "op_moved": "Spostato",
    "op_renamed": "Rinominato",
    "op_added": "Aggiunto",
    "op_deleted": "Eliminato", 
    "op_modified": "Modificato",
    "op_scanned": "Scansionato",
    "folder": "Cartella",
    "unknown": "Sconosciuto",
    "no_data": "Nessun dato da esportare!",
    "operation_filter": "Filtra per Operazione",
    "search": "Cerca",
    "extension_filter": "Filtra per Estensione",
    "date_filter": "Filtra per Data",
    "start_date": "Data Iniziale",
    "end_date": "Data Finale",
    "clear_filters": "Cancella Filtri:",
    "file_menu": "File",
    "settings": "Impostazioni",
    "options_menu": "Opzioni",
    "filters": "Filtri",
    "language": "Lingua",
    "save_as": "Salva come:",
    "save": "Salva",
    "exit": "Esci",
    "statistics": "Statistiche:",
    "no_data_to_plot": "Nessun dato da tracciare.",
    "save_all": "Salva tutto",
    "select_save_dir": "Seleziona la directory di salvataggio",
    "success": "Successo",
    "graphs_saved": "Grafici salvati con successo",
    "scanning": "Scansione...",
    "operation_timeout": "L'operazione ha richiesto troppo tempo ed è stata interrotta.",
    "memory_usage_high": "Rilevato un utilizzo elevato della memoria.",
    "error": "Errore",
    "dir_create_error": "Errore nella creazione della directory",
    "file_saved": "File salvato con successo!",
    "save_incomplete": "Esportazione incompleta!",
    "save_error": "Errore durante l'esportazione dei dati!",
    "operations_pie": "Grafico a torta",
    "file_types": "Grafico a barre",
    "timeline": "Linea del tempo",
    "tree_map": "Mappa ad albero",
    "hour_histogram": "Istogramma orario",
    "pareto_analysis": "Diagramma di Pareto",
    "operations_by_day": "Operazioni per giorno",
    "all_graphs_failed": "Errore nel salvare tutti i grafici!",
    "refresh": "Aggiorna",
    "stats_error": "Errore nella generazione delle statistiche!",
    "failure": "Fallimento",
    "graphs_saved_detail": "Grafici salvati con successo",
    "ok": "OK",
    "open_folder": "Apri cartella",
    "save_graphs_error": "Errore nel salvare i grafici!",
    "confirm": "Conferma",
    "clear_confirm": "Sei sicuro di voler cancellare i dati?",
    "clear_success": "Dati cancellati con successo!",
    "clear_error": "Errore nel cancellare i dati!",
    "preparing_scan": "Preparazione della scansione...",
    "remaining": "Rimanente",
    "scan_complete": "Scansione completata!",
    "items": "Elementi",
    "file_directory": "Directory",
    "file_image": "Immagine",
    "file_audio": "Audio",
    "file_video": "Video",
    "file_document": "Documento",
    "file_spreadsheet": "Foglio di calcolo",
    "file_presentation": "Presentazione",
    "file_database": "Database",
    "file_source_code": "Codice Sorgente",
    "file_compressed": "Compresso",
    "file_executable": "Eseguibile",
    "file_other": "Altro",
    "file_temp": "Temporaneo",
    "file_archive": "Compresso",
    "file_unknown": "File Sconosciuto",
    "file_backup": "Backup",
    "file_log": "Registro",
    "file_config": "Configurazione",
    "temporary_file": "File Temporaneo",
    "events_monitored": "Eventi Monitorati",
    "advanced_filters": "Filtri Avanzati",
    "reset_columns": "Ripristina Colonne",
    "columns_reset_success": "Colonne ripristinate con successo",
    "quantity": "Quantità",
    "date_time": "Data/Ora",
    "date": "Data",
    "hour_of_day": "Ora del Giorno",
    "cumulative_percentage": "Percentuale Cumulativa",
    "quantity_by_type": "Quantità per Tipo",
    "total_operations": "Operazioni Totali",
    "total": "Totale",
    "language_change_confirm": "Vuoi davvero ripristinare la lingua?",
    "language_change_error": "Errore durante il cambio di lingua: {}",
    "language_changed_success": "Lingua cambiata con successo!",
    "restart_error": "Impossibile riavviare l'applicazione: {}",
    "export_error": "Errore di Esportazione",
    "export_error_details": "Errore durante l'esportazione in {}: {}\n\nDettagli: {}",
    "export_preparation_error": "Errore durante la preparazione dell'esportazione: {}\n\nDettagli: {}",
    "export_success": "File esportato con successo in {}",
    "no_graphs_saved": "Nessun grafico è stato salvato con successo",
    "show_details": "Mostra Dettagli",
    "hide_details": "Nascondi Dettagli",
    "version": "Versione",
    "authors": "Autori",
    "description": "Descrizione",
    "description_text": "Gestore di file e cartelle che monitora le modifiche in una directory specifica",
    "about": "Informazioni",
    "licenses": "Licenze",
    "show_licenses": "Mostra Licenze",
    "hide_licenses": "Nascondi Licenze",
    "site_oficial": "Siti Ufficiali delle Licenze",
    "notices": "Avvisi",
    "show_notices": "Mostra Avvisi",
    "hide_notices": "Nascondi Avvisi",
    "show_privacy_policy": "Mostra Politica sulla Privacy",
    "hide_privacy_policy": "Nascondi Politica sulla Privacy",
    "visible_filters": "Filtri Visibili",
    "total_monitored": "Totale Monitorato",
    "lines": "Righe",
    "words": "Parole",
    "pages": "Pagine",
    "pages_estimated": "Pagine Stimati",
    "paragraphs": "Paragrafi",
    "slides": "Diapositive",
    "slides_estimated": "Diapositive Stimati",
    "files": "File",
    "unzipped": "Decompressi",
    "spreadsheets": "Fogli di Calcolo",
    "columns": "Colonne",
    "tables": "Tabelle",
    "lines_code": "Righe di Codice",
    "total_lines": "Totale Righe",
    "and_others": "e altri",
    "ignored": "Ignorati",
    "log_of": "Log di",
    "information_not_available": "Informazione non disponibile",
    "ignore_move_filter": "Ignora filtro di data per file spostati",
    "ignore_rename_filter": "Ignora filtro di data per file rinominati",
    "ignore_add_filter": "Ignora filtro di data per file aggiunti",
    "ignore_delete_filter": "Ignora filtro di data per file eliminati",
    "ignore_modified_filter": "Ignora filtro di data per file modificati",
    "ignore_scanned_filter": "Ignora filtro di data per file scansionati",
    "select_all_columns": "Seleziona Tutte le Colonne",
    "configure_colors": "Configura Colori",
    "operation_colors": "Colori Operazione",
    "reset_colors": "Ripristina Colori",
    "reset_colors_confirm": "Vuoi ripristinare tutti i colori ai valori predefiniti?",
    "colors_reset_success": "Colori ripristinati con successo",
    "current": "Attuale",
    "new": "Nuovo",
    "basics": "Basilari",
    "pastels": "Pastelli",
    "vibrant": "Vivaci",
    "advanced_color_picker": "Selettore Colore Avanzato",
    "cancel": "Annulla",
    "select_color": "Seleziona Colore",
    "select_color_for": "Seleziona colore per",
    "color_changed_success": "Colore cambiato con successo!",
    "basic_colors": "Colori di Base",
    "custom_colors": "Colori Personalizzati",
    "pick_screen_color": "Seleziona Colore Schermo",
    "add_to_custom_colors": "Aggiungi ai Colori Personalizzati",
    "hue": "Tinta",
    "sat": "Saturazione",
    "val": "Valore",
    "red": "Rosso",
    "green": "Verde",
    "blue": "Blu",
    "records": "Record",
    "records_estimated": "Record Stimati",
    "bytes_per_record": "Byte Per Record",
    "bytes": "Byte",
    "binary_file": "Binario",
    "minutes": "Minuti",
    "hours": "Ore",
    "days": "Dias",
    "export_options": "Opzioni di Esportazione",
    "export_active_columns": "Esporta solo colonne attive",
    "export_active_filters": "Esporta solo filtri attivi",
    "export_selected_data": "Esporta solo dati selezionati",
    "reset_export_options": "Ripristina Impostazioni Predefinite",
    "export_options_reset_success": "Opzioni di esportazione ripristinate ai valori predefiniti!",
    "no_selection": "Nessuna cella selezionata per l'esportazione.",
    "size_distribution": "Distribuzione delle Dimensioni",
    "file_size_analysis": "Analisi delle Dimensioni dei File",
    "temporal_distribution": "Distribuzione Temporale",
    "size_categories": "Categorie di Dimensione",
    "very_small": "Molto Piccolo",
    "small": "Piccolo", 
    "medium": "Medio",
    "large": "Grande",
    "very_large": "Molto Grande",
    "events_per_day": "Eventi per Giorno",
    "file_size_mb": "Dimensione del File (MB)",
    "no_size_data": "Nessun dato di dimensione disponibile",
    "boxplot_analysis": "Analisi della Distribuzione",
    "quartile_analysis": "Analisi dei Quartili",
    "temporal_distribution": "Distribuzione Temporale",
    "file_size_analysis": "Analisi delle Dimensioni dei File",
    "file_operations_flow": "Flusso di Operazioni sui File",
    "operations_by_file_type": "Operazioni per Tipo di File",
    "file_size_distribution": "Distribuzione delle Dimensioni dei File",
    "days_of_week": "Giorni della Settimana",
    "monday": "Lunedì",
    "tuesday": "Martedì",
    "wednesday": "Mercoledì",
    "thursday": "Giovedì",
    "friday": "Venerdì",
    "saturday": "Sabato",
    "sunday": "Domenica",
    "week_days": "Giorni della Settimana",
    "insufficient_data_after_filtering": "Dati insufficienti dopo il filtraggio",
    "plotly_required": "Libreria plotly necessaria per\ngenerare il Diagramma di Sankey\n\npip install plotly",
    "library_required": "Libreria necessaria",
    "install_instruction": "Per installare, esegui:",
    "time_milliseconds": "Tempo (millisecondi)",
    "time_centiseconds": "Tempo (centesimi di secondo)",
    "time_seconds": "Tempo (secondi)",
    "time_minutes": "Tempo (minuti)",
    "time_hours": "Tempo (ore)",
    "time_days": "Tempo (giorni)",
    "ms": "ms",
    "s": "s",
    "min": "min",
    "h": "h",
    "d": "g",
    "file_types": "Tipi di File",
    "select_graphs": "Seleziona Grafici",
    "select_all": "Seleziona Tutti", 
    "save_selected": "Salva Selezionati",
    "selected": "Selezionati",
    "no_graphs_selected": "Nessun grafico selezionato",
    "selected_graphs_saved_detail": "Grafici selezionati salvati: {}/{} in {}",
    "hide_selection_panel": "Nascondi Pannello di Selezione",
    "expand_selection_panel": "Espandi Pannello di Selezione",
    "notice_text": NOTICE_TEXT_IT_IT,
    "about_text": ABOUT_TEXT_IT_IT,
    "license_text": LICENSE_TEXT_IT_IT,
    "privacy_policy_text": Privacy_Policy_it_IT
}
