from GerenciamentoUI.Localizacoes.tr_08_OpcoesSobre import (LICENSE_TEXT_EN_US, 
                                                            NOTICE_TEXT_EN_US, 
                                                            ABOUT_TEXT_EN_US, 
                                                            Privacy_Policy_en_US)

traducoes_en_US = {
    "access_date": "Access Date",
    "size": "Size", 
    "attributes": "Attributes",
    "author": "Author",
    "dimensions": "Dimensions", 
    "duration": "Duration",
    "bit_rate": "Bit Rate",
    "protected": "Protected",
    "file_menu": "File",
    "settings": "Settings",
    "options_menu": "Options",
    "configure_columns": "Configure Columns",
    "filters": "Filters",
    "language": "Language",
    "yes": "Yes",
    "no": "No",
    "close": "Close",
    "readonly": "Read Only",
    "hidden": "Hidden",
    "system": "System",
    "archive": "Archive",
    "encrypted": "Encrypted", 
    "compressed": "Compressed",
    "xls": "Unknown Author - Excel",
    "access": "Unknown Author - Access",
    "outllok": "Unknown Author - Outlook",
    "publisher": "Unknown Author - Publisher",
    "visio": "Unknown Author - Visio", 
    "project": "Unknown Author - Project",
    "unknown_author": "Unknown Author",
    "text_html": "Unknown Author",
    "compressed_file": "Unknown Author - Compressed File",
    "window_title": "Panoptes Patrol",
    "select_dir": "Select Directory:",
    "start_stop": "Start/Stop Analysis:",
    "save_as": "Save As:",
    "save": "Save:",
    "exit": "Exit",
    "export_excel": "Export Excel:",
    "export_csv": "Export CSV:",
    "export_txt": "Export TXT:",
    "export_json": "Export JSON:",
    "export_xml": "Export XML:",
    "export_db": "Export DB:",
    "statistics": "Statistics:",
    "clear_data": "Clear Data:",
    "save_all": "Save All",
    "select_save_dir": "Select Directory to Save:",
    "no_dir": "No directory selected",
    "select_to_start": "Select a directory to start",
    "dir_selected": "Selected directory: {}",
    "warning": "Warning",
    "no_data_to_plot": "No data to plot.",
    "select_first": "Please select a directory first!",
    "monitoring_started": "Monitoring started...",
    "monitoring_stopped": "Monitoring stopped.",
    "data_cleared": "Data cleared.",
    "operation_type": "Operation Type",
    "name": "Name",
    "prev_dir": "Previous Directory",
    "curr_dir": "Current Directory",
    "creation_date": "Creation Date",
    "modification_date": "Modification Date",
    "type": "Type",
    "op_moved": "Moved",
    "op_renamed": "Renamed", 
    "op_added": "Added",
    "op_deleted": "Deleted",
    "op_modified": "Modified",
    "op_scanned": "Scanned",
    "folder": "Folder", 
    "unknown": "Unknown",
    "no_data": "No data to export!",
    "success": "Success",
    "graphs_saved": "Graphs saved successfully!",
    "operation_filter": "Filter by Operation",
    "search": "Search",
    "extension_filter": "Filter by Extension",
    "date_filter": "Filter by Date",
    "start_date": "Start Date",
    "end_date": "End Date",
    "clear_filters": "Clear Filters:",
    "scanning": "Scanning...",
    "operation_timeout": "The operation took too long and was interrupted.",
    "memory_usage_high": "High memory usage detected.",
    "error": "Error",
    "dir_create_error": "Error creating directory",
    "file_saved": "File saved successfully!",
    "save_incomplete": "Incomplete export!",
    "save_error": "Error exporting data!",
    "operations_pie": "Pie Chart",
    "file_types": "Bar Chart",
    "timeline": "Timeline",
    "tree_map": "Tree Map",
    "hour_histogram": "Hourly Histogram",
    "pareto_analysis": "Pareto Chart",
    "operations_by_day": "Operations per Day",
    "all_graphs_failed": "Failed to save all charts!",
    "refresh": "Refresh",
    "stats_error": "Error generating statistics!",
    "failure": "Failure",
    "graphs_saved_detail": "Charts saved successfully",
    "ok": "OK",
    "open_folder": "Open Folder",
    "save_graphs_error": "Error saving charts!",
    "confirm": "Confirm",
    "clear_confirm": "Are you sure you want to clear the data?",
    "clear_success": "Data cleared successfully!",
    "clear_error": "Error clearing data!",
    "preparing_scan": "Preparing scan...",
    "remaining": "Remaining",
    "scan_complete": "Scan complete!",
    "items": "Items",
    "file_directory": "Directory",
    "file_image": "Image",
    "file_audio": "Audio",
    "file_video": "Video",
    "file_document": "Document",
    "file_spreadsheet": "Spreadsheet",
    "file_presentation": "Presentation",
    "file_database": "Database",
    "file_source_code": "Source Code",
    "file_compressed": "Compressed",
    "file_executable": "Executable",
    "file_other": "Other",
    "file_temp": "Temporary",
    "file_archive": "Compressed",
    "file_unknown": "Unknown File",
    "file_backup": "Backup",
    "file_log": "Registry",
    "file_config": "Configuration",
    "temporary_file": "Temporary File",
    "events_monitored": "Events Monitored",
    "advanced_filters": "Advanced Filters",
    "reset_columns": "Reset Columns",
    "columns_reset_success": "Columns reset successfully",
    "quantity": "Quantity",
    "date_time": "Date/Time",
    "date": "Date",
    "hour_of_day": "Hour of Day",
    "cumulative_percentage": "Cumulative Percentage",
    "quantity_by_type": "Quantity by Type",
    "total_operations": "Total Operations",
    "total": "Total",
    "language_change_confirm": "Do you really want to reset the language?",
    "language_change_error": "Error changing language: {}",
    "language_changed_success": "Language changed successfully!",
    "restart_error": "Failed to restart application: {}",
    "export_error": "Export Error",
    "export_error_details": "Error exporting to {}: {}\n\nDetails: {}",
    "export_preparation_error": "Error preparing export: {}\n\nDetails: {}",
    "export_success": "File exported successfully to {}",
    "no_graphs_saved": "No graphs were saved successfully",
    "show_details": "Show Details",
    "hide_details": "Hide Details",
    "version": "Version",
    "authors": "Authors",
    "description": "Description",
    "description_text": "File and folder manager that monitors changes in a specific directory",
    "about": "About",
    "licenses": "Licenses",
    "show_licenses": "Show Licenses",
    "hide_licenses": "Hide Licenses",
    "site_oficial": "Official License Sites",
    "notices": "Notices",
    "show_notices": "Show Notices",
    "hide_notices": "Hide Notices",
    "show_privacy_policy": "Show Privacy Policy",
    "hide_privacy_policy": "Hide Privacy Policy",
    "visible_filters": "Visible Filters",
    "total_monitored": "Total Monitored",
    "lines": "Lines",
    "words": "Words",
    "pages": "Pages",
    "pages_estimated": "Estimated Pages",
    "paragraphs": "Paragraphs",
    "slides": "Slides",
    "slides_estimated": "Estimated Slides",
    "files": "Files",
    "unzipped": "Unzipped",
    "spreadsheets": "Spreadsheets",
    "columns": "Columns",
    "tables": "Tables",
    "lines_code": "Lines of Code",
    "total_lines": "Total Lines",
    "and_others": "and others",
    "ignored": "Ignored",
    "log_of": "Log of",
    "information_not_available": "Information not available",
    "ignore_move_filter": "Ignore date filter for moved files",
    "ignore_rename_filter": "Ignore date filter for renamed files",
    "ignore_add_filter": "Ignore date filter for added files",
    "ignore_delete_filter": "Ignore date filter for deleted files",
    "ignore_modified_filter": "Ignore date filter for modified files",
    "ignore_scanned_filter": "Ignore date filter for scanned files",
    "select_all_columns": "Select All Columns",
    "configure_colors": "Configure Colors",
    "operation_colors": "Operation Colors",
    "reset_colors": "Reset Colors",
    "reset_colors_confirm": "Do you want to reset all colors to default values?",
    "colors_reset_success": "Colors reset successfully!",
    "current": "Current",
    "new": "New",
    "basics": "Basics",
    "pastels": "Pastels",
    "vibrant": "Vibrants",
    "advanced_color_picker": "Advanced Color Picker",
    "cancel": "Cancel",
    "select_color": "Select Color",
    "select_color_for": "Select color for",
    "color_changed_success": "Color changed successfully!",
    "basic_colors": "Basic Colors",
    "custom_colors": "Customize Colors",
    "pick_screen_color": "Pick Screen Color",
    "add_to_custom_colors": "Add to Custom Colors",
    "hue": "Hue",
    "sat": "Saturation",
    "val": "Value",
    "red": "Red",
    "green": "Green",
    "blue": "Blue",
    "records": "Records",
    "records_estimated": "Estimated Records",
    "bytes_per_record": "Bytes Per Record",
    "bytes": "Bytes",
    "binary_file": "Binary",
    "minutes": "Minutes",
    "hours": "Hours",
    "days": "Days",
    "export_options": "Export Options",
    "export_active_columns": "Export only active columns",
    "export_active_filters": "Export only active filters",
    "export_selected_data": "Export only selected data",
    "reset_export_options": "Reset Defaults",
    "export_options_reset_success": "Export options restored to default values!",
    "no_selection": "No cells selected for export.",
    "size_distribution": "Size Distribution",
    "file_size_analysis": "File Size Analysis",
    "temporal_distribution": "Temporal Distribution",
    "size_categories": "Size Categories",
    "very_small": "Very Small",
    "small": "Small", 
    "medium": "Medium",
    "large": "Large",
    "very_large": "Very Large",
    "events_per_day": "Events per Day",
    "file_size_mb": "File Size (MB)",
    "no_size_data": "No size data available",
    "boxplot_analysis": "Distribution Analysis",
    "quartile_analysis": "Quartile Analysis",
    "temporal_distribution": "Temporal Distribution",
    "file_size_analysis": "File Size Analysis",
    "file_operations_flow": "File Operations Flow",
    "operations_by_file_type": "Operations by File Type",
    "file_size_distribution": "File Size Distribution",
    "days_of_week": "Days of the Week",
    "monday": "Monday",
    "tuesday": "Tuesday",
    "wednesday": "Wednesday",
    "thursday": "Thursday",
    "friday": "Friday",
    "saturday": "Saturday",
    "sunday": "Sunday",
    "week_days": "Week Days",
    "insufficient_data_after_filtering": "Insufficient data after filtering",
    "plotly_required": "Plotly library required to\ngenerate Sankey Diagram\n\npip install plotly",
    "library_required": "Library required",
    "install_instruction": "To install, run:",
    "time_milliseconds": "Time (milliseconds)",
    "time_centiseconds": "Time (centiseconds)",
    "time_seconds": "Time (seconds)",
    "time_minutes": "Time (minutes)",
    "time_hours": "Time (hours)",
    "time_days": "Time (days)",
    "ms": "ms",
    "s": "s",
    "min": "min",
    "h": "h",
    "d": "d",
    "file_types": "File Types",
    "select_graphs": "Select Graphs",
    "select_all": "Select All", 
    "save_selected": "Save Selected",
    "selected": "Selected",
    "no_graphs_selected": "No graphs selected",
    "selected_graphs_saved_detail": "Selected graphs saved: {}/{} in {}",
    "hide_selection_panel": "Hide Selection Panel",
    "expand_selection_panel": "Expand Selection Panel",
    "notice_text": NOTICE_TEXT_EN_US,
    "about_text": ABOUT_TEXT_EN_US,
    "license_text": LICENSE_TEXT_EN_US,
    "privacy_policy_text": Privacy_Policy_en_US
}
