from GerenciamentoUI.Localizacoes.tr_08_OpcoesSobre import (LICENSE_TEXT_FR_FR,
                                                            NOTICE_TEXT_FR_FR, 
                                                            ABOUT_TEXT_FR_FR, 
                                                            Privacy_Policy_fr_FR)

traducoes_fr_FR = {
    "access_date": "Date d'Accès",
    "size": "Taille",
    "attributes": "Attributs",
    "author": "Auteur",
    "dimensions": "Dimensions",
    "duration": "Durée",
    "bit_rate": "Débit Binaire",
    "protected": "Protégé",
    "configure_columns": "Configurer Colonnes",
    "yes": "Oui",
    "no": "Non",
    "close": "Fermer",
    "readonly": "Lecture Seule",
    "hidden": "Masqué",
    "system": "Système",
    "archive": "Archive",
    "encrypted": "Chiffré",
    "compressed": "Compressé",
    "xls": "Auteur Inconnu - Excel",
    "access": "Auteur Inconnu - Access",
    "outllok": "Auteur Inconnu - Outlook",
    "publisher": "Auteur Inconnu - Publisher",
    "visio": "Auteur Inconnu - Visio",
    "project": "Auteur Inconnu - Project",
    "unknown_author": "Auteur Inconnu",
    "text_html": "Auteur Inconnu",
    "compressed_file": "Auteur Inconnu - Fichier Compressé",
    "window_title": "Panoptes Patrol",
    "select_dir": "Sélectionner Répertoire:",
    "start_stop": "Démarrer/Arrêter l'Analyse:",
    "export_excel": "Exporter Excel:",
    "export_csv": "Exporter CSV:",
    "export_txt": "Exporter TXT:",
    "export_json": "Exporter JSON:",
    "export_xml": "Exporter XML:",
    "export_db": "Exporter DB:",
    "clear_data": "Effacer Données:",
    "no_dir": "Aucun répertoire sélectionné",
    "select_to_start": "Sélectionnez un répertoire pour commencer",
    "dir_selected": "Répertoire sélectionné: {}",
    "warning": "Avertissement",
    "select_first": "Veuillez sélectionner un répertoire!",
    "monitoring_started": "Surveillance démarrée...",
    "monitoring_stopped": "Surveillance arrêtée.",
    "data_cleared": "Données effacées.",
    "operation_type": "Type d'Opération",
    "name": "Nom",
    "prev_dir": "Répertoire Précédent",
    "curr_dir": "Répertoire Actuel",
    "creation_date": "Date de Création",
    "modification_date": "Date de Modification",
    "type": "Type",
    "op_moved": "Déplacé",
    "op_renamed": "Renommé",
    "op_added": "Ajouté",
    "op_deleted": "Supprimé",
    "op_modified": "Modifié",
    "op_scanned": "Scanné",
    "folder": "Dossier",
    "unknown": "Inconnu",
    "no_data": "Pas de données à exporter!",
    "operation_filter": "Filtrer par Opération",
    "search": "Rechercher",
    "extension_filter": "Filtrer par Extension",
    "date_filter": "Filtrer par Date",
    "start_date": "Date de Début",
    "end_date": "Date de Fin",
    "clear_filters": "Effacer les Filtres:",
    "file_menu": "Fichier",
    "settings": "Paramètres",
    "options_menu": "Options",
    "filters": "Filtres",
    "language": "Langue",
    "save_as": "Enregistrer sous:",
    "save": "Enregistrer",
    "exit": "Quitter",
    "statistics": "Statistiques:",
    "no_data_to_plot": "Pas de données à tracer.",
    "save_all": "Tout enregistrer",
    "select_save_dir": "Sélectionner le dossier de sauvegarde",
    "success": "Succès",
    "graphs_saved": "Graphiques enregistrés avec succès",
    "scanning": "Balayage...",
    "operation_timeout": "L'opération a pris trop de temps et a été interrompue.",
    "memory_usage_high": "Utilisation élevée de la mémoire détectée.",
    "error": "Erreur",
    "dir_create_error": "Erreur lors de la création du répertoire",
    "file_saved": "Fichier enregistré avec succès !",
    "save_incomplete": "Exportation incomplète !",
    "save_error": "Erreur lors de l'exportation des données !",
    "operations_pie": "Diagramme circulaire",
    "file_types": "Graphique à barres",
    "timeline": "Chronologie",
    "tree_map": "Arborescence",
    "hour_histogram": "Histogramme horaire",
    "pareto_analysis": "Diagramme de Pareto",
    "operations_by_day": "Opérations par jour",
    "all_graphs_failed": "Échec de l'enregistrement de tous les graphiques !",
    "refresh": "Rafraîchir",
    "stats_error": "Erreur lors de la génération des statistiques !",
    "failure": "Échec",
    "graphs_saved_detail": "Graphiques enregistrés avec succès",
    "ok": "OK",
    "open_folder": "Ouvrir le dossier",
    "save_graphs_error": "Erreur lors de l'enregistrement des graphiques !",
    "confirm": "Confirmer",
    "clear_confirm": "Êtes-vous sûr de vouloir effacer les données ?",
    "clear_success": "Données effacées avec succès !",
    "clear_error": "Erreur lors de l'effacement des données !",
    "preparing_scan": "Préparation de l'analyse...",
    "remaining": "Restant",
    "scan_complete": "Analyse terminée !",
    "items": "Éléments",
    "file_directory": "Répertoire",
    "file_image": "Image",
    "file_audio": "Audio",
    "file_video": "Vidéo",
    "file_document": "Document",
    "file_spreadsheet": "Feuille de calcul",
    "file_presentation": "Présentation",
    "file_database": "Base de données",
    "file_source_code": "Code Source",
    "file_compressed": "Compressé",
    "file_executable": "Exécutable",
    "file_other": "Autre",
    "file_temp": "Temporaire",
    "file_archive": "Compressé",
    "file_unknown": "Fichier Inconnu",
    "file_backup": "Sauvegarde",
    "file_log": "Registre",
    "file_config": "Configuration",
    "temporary_file": "Fichier Temporaire",
    "events_monitored": "Événements surveillés",
    "advanced_filters": "Filtres avancés",
    "reset_columns": "Réinitialiser les colon",
    "columns_reset_success": "Colonnes réinitialisées avec succès",
    "quantity": "Quantité",
    "date_time": "Date/Heure",
    "date": "Date",
    "hour_of_day": "Heure du Jour",
    "cumulative_percentage": "Pourcentage Cumulé",
    "quantity_by_type": "Quantité par Type",
    "total_operations": "Total des Opérations",
    "total": "Total",
    "language_change_confirm": "Voulez-vous vraiment réinitialiser la langue ?",
    "language_change_error": "Erreur lors du changement de langue : {}",
    "language_changed_success": "Langue changée avec succès !",
    "restart_error": "Échec du redémarrage de l'application : {}",
    "export_error": "Erreur d'Exportation",
    "export_error_details": "Erreur lors de l'exportation vers {}: {}\n\nDétails: {}",
    "export_preparation_error": "Erreur lors de la préparation de l'exportation: {}\n\nDétails: {}",
    "export_success": "Fichier exporté avec succès vers {}",
    "no_graphs_saved": "Aucun graphique n'a été enregistré avec succès",
    "show_details": "Afficher les Détails",
    "hide_details": "Masquer les Détails",
    "version": "Version",
    "authors": "Auteurs",
    "description": "Description",
    "description_text": "Gestionnaire de fichiers et de dossiers qui surveille les modifications dans un répertoire spécifique",
    "about": "À propos",
    "licenses": "Licences",
    "show_licenses": "Afficher les Licences",
    "hide_licenses": "Masquer les Licences",
    "site_oficial": "Sites Officiels des Licences",
    "notices": "Avis",
    "show_notices": "Afficher les Avis",
    "hide_notices": "Masquer les Avis",
    "show_privacy_policy": "Afficher la Politique de Confidentialité",
    "hide_privacy_policy": "Masquer la Politique de Confidentialité",
    "visible_filters": "Filtres Visibles",
    "total_monitored": "Total Surveillé",
    "lines": "Lignes",
    "words": "Mots",
    "pages": "Pages",
    "pages_estimated": "Pages Estimées",
    "paragraphs": "Paragraphes",
    "slides": "Diapositives",
    "slides_estimated": "Diapositives Estimées",
    "files": "Fichiers",
    "unzipped": "Décompressés",
    "spreadsheets": "Feuilles de Calcul",
    "columns": "Colonnes",
    "tables": "Tables",
    "lines_code": "Lignes de Code",
    "total_lines": "Total des Lignes",
    "and_others": "et autres",
    "ignored": "Ignorés",
    "log_of": "Journal de",
    "information_not_available": "Information non disponible",
    "ignore_move_filter": "Ignorer le filtre de date pour les fichiers déplacés",
    "ignore_rename_filter": "Ignorer le filtre de date pour les fichiers renommés",
    "ignore_add_filter": "Ignorer le filtre de date pour les fichiers ajoutés",
    "ignore_delete_filter": "Ignorer le filtre de date pour les fichiers supprimés",
    "ignore_modified_filter": "Ignorer le filtre de date pour les fichiers modifiés",
    "ignore_scanned_filter": "Ignorer le filtre de date pour les fichiers scannés",
    "select_all_columns": "Sélectionner Toutes les Colonnes",
    "configure_colors": "Configurer les Couleurs",
    "operation_colors": "Couleurs d'Opération",
    "reset_colors": "Réinitialiser les Couleurs",
    "reset_colors_confirm": "Voulez-vous réinitialiser toutes les couleurs aux valeurs par défaut?",
    "colors_reset_success": "Couleurs réinitialisées avec succès !",
    "current": "Actuel",
    "new": "Nouveau",
    "basics": "Basique",
    "pastels": "Pastels",
    "vibrant": "Vibrants",
    "advanced_color_picker": "Sélecteur de Couleur Avancé",
    "cancel": "Annuler",
    "select_color": "Sélectionner la Couleur",
    "select_color_for": "Sélectionner la couleur pour",
    "color_changed_success": "Couleur changée avec succès!",
    "basic_colors": "Couleurs de Base",
    "custom_colors": "Personnaliser les Couleurs",
    "pick_screen_color": "Sélectionner la Couleur de l'Écran",
    "add_to_custom_colors": "Ajouter aux Couleurs Personnalisées",
    "hue": "Teinte",
    "sat": "Saturation",
    "val": "Valeur",
    "red": "Rouge",
    "green": "Vert",
    "blue": "Bleu",
    "records": "Enregistrements",
    "records_estimated": "Enregistrements Estimés",
    "bytes_per_record": "Octets Par Enregistrement",
    "bytes": "Octets",
    "binary_file": "Fichier Binaire",
    "minutes": "Minutes",
    "hours": "Heures",
    "days": "Jours",
    "notice_text": NOTICE_TEXT_FR_FR,
    "about_text": ABOUT_TEXT_FR_FR,
    "license_text": LICENSE_TEXT_FR_FR,
    "privacy_policy_text": Privacy_Policy_fr_FR
}
